const int palettes[] = 
{
    CGA_BW, /* Unused index 0 */
    CGA_BW, /* 1 */
    CGA_CYAN, 
    CGA_YELLOW, 
    CGA_BW, 
    CGA_CYAN, /* 5 */
    CGA_YELLOW, 
    CGA_YELLOW, 
    CGA_YELLOW, 
    CGA_CYAN, 
    CGA_YELLOW, /* 10 */
    CGA_YELLOW, 
    CGA_YELLOW, 
    CGA_BW, 
    CGA_BW, 
    CGA_BW, /* 15 */
    CGA_BW, 
    CGA_BW, 
    CGA_BW, 
    CGA_BW, 
    CGA_BW, /* 20 */
    CGA_YELLOW 
};
